#+TITLE: org-outlook.el
#+AUTHOR: Matthew L. Fidler
* Library Information
 /org-outlook.el/ --- Outlook org

 - Filename :: [[file:org-outlook.el][org-outlook.el]]
Description: 
 - Author :: Matthew L. Fidler
Maintainer:
 - Created :: Mon May 10 09:44:59 2010 (-0500)
 - Version :: 0.12
 - Last-Updated :: Tue May 29 22:21:06 2012 (-0500)
 -           By :: Matthew L. Fidler
 -     Update # :: 166
 - URL :: https://github.com/mlf176f2/org-outlook.el
 - Keywords :: Org-outlook 
Compatibility:

* Introduction:
Org mode lets you organize your tasks. However, sometimes you may wish
to integrate org-mode with outlook since your company forces you to
use Microsoft Outlook.  [[file:org-outlook.el][org-outlook.el]] allows: 

- Creating Tasks from outlook items:
  - org-outlook-task. All selected items in outlook will be added to a
    task-list at current point. This version requires org-protocol and   
    org-protocol.vbs.  The org-protocol.vbs has can be generated with
    the interactive function =org-outlook-create-vbs=.

  - If your organization has blocked all macro access OR you want to
    have an action for a saved =.msg= email, org-outlook also adds
    drag and drop support allowing =.msg= files to become org tasks.
    This is enabled by default, but can be disabled by
    =org-outlook-no-dnd=

  - With blocked emails, you may wish to delete the emails in a folder
    after the task is completed.  This can be accomplished with
    =org-protocol-delete-msgs=.  If you use it frequently, you may
    wish to bind it to a key, like

#+BEGIN_SRC emacs-lisp
  (define-key org-mode-map (kbd "C-c d") 'org-protocol-delete-msgs)
#+END_SRC


- Open Outlook Links in org-mode

  - Requires org-outlook-location to be customized when using Outlook
    2007 (this way you don’t have to edit the registry).

This is based loosely on:
http://superuser.com/questions/71786/can-i-create-a-link-to-a-specific-email-message-in-outlook


Note that you may also add tasks using visual basic directly. The script below performs the following actions:

   - Move email to Personal Folders under folder "@ActionTasks" (changes GUID)
   - Create a org-mode task under heading "* Tasks" for the file =f:\Documents\org\gtd.org=
   - Note by replacing "@ActionTasks", "* Tasks" and
     =f:\Documents\org\gtd.org= you can modify this script to your
     personal needs.

The visual basic script for outlook can be created by calling =M-x org-outlook-create-vbs=

* Functions
** Interactive Functions

** Internal Functions
* Variables
** Customizable Variables

** Internal Variables
* History

7-Aug-2014    Matthew L. Fidler  
   Last-Updated: Tue May 29 22:21:06 2012 (-0500) #166 (Matthew L. Fidler)
   Add autoload cookie for org-outlook-enable-msg-dnd
1-Jul-2014    Matthew L. Fidler  
   Last-Updated: Tue May 29 22:21:06 2012 (-0500) #166 (Matthew L. Fidler)
   Add delete msg files support
 - 24-Jun-2014 ::  Bugfix for Drag and Drop Support (Matthew L. Fidler)
 - 24-Jun-2014 ::  Add Drag and drop support for tasks (Matthew L. Fidler)
 - 12-Dec-2012 ::  Updated Visual Basic Script to be more robust, and have more options. (Matthew L. Fidler)
 - 07-Dec-2012 ::  Should fix Issue #1. Also added org-outlook-create-vbs to create the VBS code based on a user's setup. (Matthew L. Fidler)
 - 26-May-2012 ::  Added (require 'cl), Thanks Robert Pluim (Matthew L. Fidler)
 - 21-Feb-2012 ::  Bug fix for opening files. (Matthew L. Fidler)
 - 21-Feb-2012 ::  Bug fix. (Matthew L. Fidler)
 - 13-Dec-2011 ::  Added more autoload cookies. (Matthew L. Fidler)
 - 08-Apr-2011 ::  Added some autoload cookies. (US041375)
 - 15-Feb-2011 ::  Changed outlook-org to org-outlook.el (Matthew L. Fidler)
 - 11-Jan-2011 ::  Finalized interface with org-protocol (Matthew L. Fidler)
 - 05-Jan-2011 ::  Removed outlook copy. I only use from outlook now.  (Matthew L. Fidler)
